name = "JuliaPresentation"
uuid = "b208896a-798b-4ac2-a1ed-3f987ed4a149"
authors = ["Guillaume Cleroux <cleg1805@usherbrooke.ca> and contributors"]
version = "0.1.0"

[deps]
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"

[compat]
Pluto = "0.19"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
